---
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rest_api
      - POSTGRES_DB=rest_api
      - POSTGRES_PASSWORD=P@ss
    mem_limit: 256m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - services_network
networks:
  services_network:
    external: true
